### ISSUE TITLE
Can't install packages via "Catalog Browser"

### ISSUE THREAD

**Issue by lispercat** [mumez/pharo-vnc-supervisor#4] opened 2018-04-07 15:51 UTC
If you try to install any project via the catalog browser it will give you an error.
World->tools->Catalog Browser, right-click on "Animation" package and select "Install stable version".
You will see it fail with the error: "There was an error trying to install Animation"

I am doing it inside Windows 10, docker toolbox, after running the image using following command:
docker run --name my_pharo -d -p 5901:5901 -p 6901:6901 mumez/pharo-vnc-supervisor

**Comment by mumez** [comment] 2018-04-09 03:50
I think it is specific to the Animation package. When I tried installing Animation package in local (non-docker, macOS) Pharo environment, it still raised the same error that you encountered.

![error-on-mac-os-pharo](https://user-images.githubusercontent.com/705350/38478563-8026617e-3bf4-11e8-984c-c57b2f1387c6.png)

**Comment by mumez** [comment] 2018-04-09 04:00
For clarification, I tried "Tarantalk" package via Catalog Browser in "pharo-vnc-supervisor" image.  It was successful and I was able to verify the installed version in Versionner.

![successful-tarantool-installation-on-docker](https://user-images.githubusercontent.com/705350/38478679-544ff55a-3bf5-11e8-8b30-50cceae3ac9c.png)

**Comment by mumez** [comment] 2018-04-09 04:04
"Animation" package seems to be not including 'stable' definition on ConfigurationOfAnimation. I think it is the cause of the problem. 

![no-stable-definition-in-configuration-of-animation](https://user-images.githubusercontent.com/705350/38478857-65cd0d94-3bf6-11e8-986a-179e28327cf2.png)

**Comment by mumez** [comment] 2018-04-09 14:50
OK, so please attach the screenshot showing that you failed in other package. I tried by myself in https://github.com/mumez/pharo-vnc-supervisor/issues/4#issuecomment-379623636. 
At least, I succeeded installation in "Tarantalk" package.

**Comment by mumez** [comment] 2018-04-09 14:53
And please try installing "Animation" package in standard (non-docker) Pharo environment. I think it still fails.

**Comment by mumez** [comment] 2018-04-15 06:44
I put https://github.com/mumez/teapot-pharo-vnc-supervisor
It is an example of installing "Teapot" package listed in Catalog Browser with Dockerfile.

**Comment by mumez** [comment] 2018-05-21 06:42
Now I close the issue. Please provide more info if you would like to reopen.

**Closed** 2018-05-21 06:42 UTC
